version: '3.9'

services:
  # fiber-app:
  #   image: imageName
  #   depends_on: 마지막에

  redis-db:
    image: redis
    expose:
      - 6379
    volumes:
      - ./redis_db:/data
    command:
      - --save 60 1
      - --loglevel warning

  postgresql-db:
    image: postgres
    volumes:
      - ./postgresql_db/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=menu
      - POSTGRES_PASSWORD=docker123
    expose:
      - 5432

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=hssong1024@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=docker123
    ports:
      - 5050:80
    depends_on:
      - postgresql-app
