version: '3.9'

services:
  fiber-app:
    image: golang
    volumes:
      - ./fiber_app:/myapp
    working_dir: /myapp
    ports:
      - 80:3000
    command: ["go", "run", "main.go"]
    depends_on:
      - redis-db
      - postgresql-db

  redis-db:
    image: redis
    expose:
      - 6379
    volumes:
      - ./redis_db:/data
    command: ["redis-server", "--save 60 1", "--loglevel warning"]

  postgresql-db:
    build: ./postgresql_db
    volumes:
      - ./postgresql_db/pgdata:/var/lib/postgresql/data/pgdata


  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=hssong1024@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=docker123
    ports:
      - 5050:80
    depends_on:
      - postgresql-db

# docker run -it --network menu-board_default redis-cli -h redis-db